create table AK_VOC_BROWSING_CUSTOMERS as
(SELECT
s.VISITOR_KEY,
s.SESSION_KEY,
v.MARKETING_CLOUD_VISITOR_ID,
v.SURVEY_FREE_FORM_ANSWER_TEXT,
case when (SURVEY_FREE_FORM_ANSWER_TEXT like '%not ready%'
or SURVEY_FREE_FORM_ANSWER_TEXT like '%still thinking%'
or SURVEY_FREE_FORM_ANSWER_TEXT like '%research%'
or SURVEY_FREE_FORM_ANSWER_TEXT like '%decide%to buy%') then 'Researching'
when (SURVEY_FREE_FORM_ANSWER_TEXT like '%just look%'
or SURVEY_FREE_FORM_ANSWER_TEXT like '%browsing%') then 'Browsing' end as profile
FROM ACTIVITY.ACTIVITY.DIGITAL_SITE_SURVEY_RESPONSE v
inner join CLICKSTREAM.CLICKSTREAM.SESSION s using(MARKETING_CLOUD_VISITOR_ID)
where (DIGITAL_SITE_SURVEY_KEY=2)
and RESPONSE_DATE_KEY BETWEEN 20180101 and 20190701
and (QUESTION_CODE='QID11-TEXT')
and MARKETING_CLOUD_VISITOR_ID is not null
and SURVEY_FREE_FORM_ANSWER_TEXT is not null
and (SURVEY_FREE_FORM_ANSWER_TEXT like '%not ready%'
or SURVEY_FREE_FORM_ANSWER_TEXT like '%still thinking%'
or SURVEY_FREE_FORM_ANSWER_TEXT like '%just look%'
or SURVEY_FREE_FORM_ANSWER_TEXT like '%research%'
or SURVEY_FREE_FORM_ANSWER_TEXT like '%decide%to buy%'
or SURVEY_FREE_FORM_ANSWER_TEXT like '%browsing%'
)
)
7/